[settings]
# tools can read the versions files used by other version managers
# for example, .nvmrc in the case of node's nvm
idiomatic_version_file_enable_tools = [
  "dotnet",
  "elixir",
  "go",
  "haskell",
  "java",
  "javascript",
  "kotlin",
  "node",
  "python",
  "ruby",
  "rust",
  "scala",
]
experimental = true
fetch_remote_versions_timeout = "30s"

[settings.ruby]
compile = false

[settings.python]
github_attestations = false
