#!/usr/bin/env zsh

# vim:filetype=zsh syntax=zsh tabstop=2 shiftwidth=2 softtabstop=2 expandtab autoindent fileencoding=utf-8

# git command: cc

# Source shell helpers if they aren't already loaded
type is_shellrc_sourced 2>&1 &> /dev/null || source "${HOME}/.shellrc"

# Note: Use a function so that it can accept parameters
_cc() {
  local folder="${1:-$(pwd)}"
  section_header "$(yellow 'Compressing') $(purple "${folder}")"
  if ! is_git_repo "${folder}"; then
    warn "Skipping finding size of the repo since '$(yellow "${folder}")' doesn't exist or is not a git repo"
  else
    git -C "${folder}" cc
  fi
}

cc() {
  if is_executable "${PERSONAL_BIN_DIR}/cc-${PWD##*/}.sh"; then
    . "${PERSONAL_BIN_DIR}/cc-${PWD##*/}.sh" "$@"
  else
    _cc "$@"
  fi
}

cc "$@"
compdef cc
