#!/usr/bin/env zsh

# vim:filetype=zsh syntax=zsh tabstop=2 shiftwidth=2 softtabstop=2 expandtab autoindent fileencoding=utf-8

# git command: push

# Source shell helpers if they aren't already loaded
type is_shellrc_sourced 2>&1 &> /dev/null || source "${HOME}/.shellrc"

# Note: Use a function so that it can accept parameters
_push() {
  local folder
  local -a switches
  for arg in "$@"; do
    if [[ "${arg}" == --* ]]; then
      switches+=("${arg}")
    elif is_zero_string "${folder}"; then
      folder="${arg}"
    fi
  done
  folder="${folder:-$(pwd)}"
  section_header "$(yellow 'Pushing') $(purple "${folder}")"
  if ! is_git_repo "${folder}"; then
    warn "Skipping pushing of the repo since '$(yellow "${folder}")' doesn't exist or is not a git repo"
  else
    git -C "${folder}" push "${switches[@]}"
  fi
}

push() {
  if is_executable "${PERSONAL_BIN_DIR}/push-${PWD##*/}.sh"; then
    . "${PERSONAL_BIN_DIR}/push-${PWD##*/}.sh" "$@"
  else
    _push "$@"
  fi
}

push "$@"
compdef push
