#!/usr/bin/env zsh

# vim:filetype=zsh syntax=zsh tabstop=2 shiftwidth=2 softtabstop=2 expandtab autoindent fileencoding=utf-8

# Source shell helpers if they aren't already loaded
type is_shellrc_sourced 2>&1 &> /dev/null || source "${HOME}/.shellrc"

# Reports status of the following repos: HOME, DOTFILES_DIR, PERSONAL_PROFILES_DIR, ZenProfile chrome folder
status_all_repos() {
  st "${HOME}"
  st "${DOTFILES_DIR}"
  st "${PERSONAL_PROFILES_DIR}"
  # Use zsh glob qualifiers to only loop if matches exist and are directories
  # (N) nullglob: if no match, the pattern expands to nothing
  # (/): only match directories
  local chrome_folders=("${PERSONAL_PROFILES_DIR}"/*Profile/Profiles/DefaultProfile/chrome(N/))
  if [[ ${#chrome_folders[@]} -gt 0 ]]; then
    for folder in "${chrome_folders[@]}"; do
      st "${folder}"
    done
    unset folder
  fi
}

status_all_repos "$@"
compdef status_all_repos
